[package]
name = "pallet-staking"
version = "2.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet staking"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/std" }
sp-phragmen = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/phragmen" }
sp-io ={ path = "../../primitives/io", default-features = false , version = "2.0.0-alpha.2"}
sp-runtime = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/runtime" }
sp-staking = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/staking" }
frame-support = { version = "2.0.0-alpha.2", default-features = false, path = "../support" }
frame-system = { version = "2.0.0-alpha.2", default-features = false, path = "../system" }
pallet-session = { version = "2.0.0-alpha.2", features = ["historical"], path = "../session", default-features = false }
pallet-authorship = { version = "2.0.0-alpha.2", default-features = false, path = "../authorship" }
sp-application-crypto = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/application-crypto" }

# Optional imports for tesing-utils feature
pallet-indices = { version = "2.0.0-alpha.2", optional = true, path = "../indices" }
sp-core = { version = "2.0.0-alpha.2", optional = true, path = "../../primitives/core" }
rand = { version = "0.7.3", optional = true }

[dev-dependencies]
pallet-balances = { version = "2.0.0-alpha.2", path = "../balances" }
pallet-timestamp = { version = "2.0.0-alpha.2", path = "../timestamp" }
pallet-staking-reward-curve = { version = "2.0.0-alpha.2",  path = "../staking/reward-curve" }
substrate-test-utils = { version = "2.0.0-alpha.2", path = "../../test-utils" }
parking_lot = { version = "0.10.0" }
env_logger = "0.7.1"

[features]
migrate = []
testing-utils = [
	"std",
	"pallet-indices/std",
	"sp-core/std",
	"rand/std",
]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-phragmen/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-core/std",
]
