[package]
name = "sp-stats"
version = "2.0.0-alpha.2"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate Statistics"
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sp-stats"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-runtime-interface = { version = "2.0.0-alpha.2", path = "../runtime-interface", default-features = false}

[features]
default = [ "std" ]
std = [
	"sp-runtime-interface/std"
]
